name: Upload Router Config

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Make
        run: sudo apt-get install make

      - name: Build Config File
        run: make

      - name: 删除发布
        if: ${{ github.event.inputs.confirm == 'true' }}
        run: |
          # 获取所有发布
          releases=$(curl -s -X GET -H "Accept: application/vnd.github.v3+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/releases" | jq -r '.[].id')

          # 删除发布
          for release in $releases; do
            curl -s -X DELETE -H "Accept: application/vnd.github.v3+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/releases/$release"
          done
          
      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: v1.0.0
          name: k v1.0.0
          body: TODO New Release.
          draft: false
          prerelease: false
          files: |
            routes4.conf
            routes6.conf        
