name: Upload Router Config

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
    push:
      tags:
        - "v1.0.0"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Make
        run: sudo apt-get install make

      - name: Build Config File
        run: make      
          
      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'v1.0.0')
        with:
          tag_name: v1.0.0
          name: k v1.0.0
          body: TODO New Release.
          draft: false
          prerelease: false
          files: |
            routes4.conf
            routes6.conf  
