name: Upload Router Config

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'debug'

jobs:
  delete_all_releases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Delete Tags
        run: |
          git fetch --prune --prune-tags
          git tag -l | xargs -I @ git push --delete origin @
