name: Upload Router Config

on:
  schedule:
    - cron: '0 19 * * *'
  push:
    branches:
      - main        

jobs:
  delete_all_releases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Delete Tags
        run: |
          git fetch --prune --prune-tags
          git tag -l | xargs -I @ git push --delete origin @
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Build router configuration file
        run: make

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          body_path: ${{ github.workspace }}
        with:
          tag_name: v1.0.0
          files: |
            routes4.conf
            routes6.conf            
          
